-- Music Store SQL Analysis Project


-- Customer analysis

-- 1. Get all customers located in the USA
SELECT *
FROM customer
WHERE country = 'USA';


-- 2. Count number of customers in each country
SELECT country, COUNT(*) AS total_customers
FROM customer
GROUP BY country
ORDER BY total_customers DESC;


-- 3. Find the top 10 customers who spent the most
SELECT c.customer_id, c.first_name, c.last_name, SUM(i.total) AS total_spent
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;



-- Sales analysis

-- 4. Calculate total revenue generated by each country
SELECT billing_country, SUM(total) AS total_revenue
FROM invoice
GROUP BY billing_country
ORDER BY total_revenue DESC;


-- 5. Find the average invoice value
SELECT AVG(total) AS average_invoice_value
FROM invoice;


-- 6. Get the top 5 highest value invoices
SELECT invoice_id, total
FROM invoice
ORDER BY total DESC
LIMIT 5;



-- Track and genre analysis

-- 7. Identify the most purchased music genres
SELECT g.name AS genre, COUNT(il.quantity) AS purchase_count
FROM genre g
JOIN track t ON g.genre_id = t.genre_id
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY g.name
ORDER BY purchase_count DESC;


-- 8. Find the top 10 most purchased tracks
SELECT t.name AS track_name, COUNT(il.quantity) AS purchase_count
FROM track t
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY t.name
ORDER BY purchase_count DESC
LIMIT 10;


-- 9. Calculate revenue generated by each genre
SELECT g.name AS genre, SUM(il.unit_price * il.quantity) AS total_sales
FROM genre g
JOIN track t ON g.genre_id = t.genre_id
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY g.name
ORDER BY total_sales DESC;



-- Artist analysis

-- 10. Find artists with the highest number of tracks
SELECT ar.name AS artist, COUNT(t.track_id) AS total_tracks
FROM artist ar
JOIN album al ON ar.artist_id = al.artist_id
JOIN track t ON al.album_id = t.album_id
GROUP BY ar.name
ORDER BY total_tracks DESC;


-- 11. Find artists that generated the most revenue
SELECT ar.name AS artist, SUM(il.unit_price * il.quantity) AS total_revenue
FROM artist ar
JOIN album al ON ar.artist_id = al.artist_id
JOIN track t ON al.album_id = t.album_id
JOIN invoice_line il ON t.track_id = il.track_id
GROUP BY ar.name
ORDER BY total_revenue DESC
LIMIT 10;



-- Additional insights

-- 12. Find top spending customers in each country
SELECT billing_country, customer_id, SUM(total) AS total_spent
FROM invoice
GROUP BY billing_country, customer_id
ORDER BY billing_country, total_spent DESC;


-- 13. Count how many tracks each customer purchased
SELECT c.customer_id, c.first_name, c.last_name, COUNT(il.quantity) AS tracks_purchased
FROM customer c
JOIN invoice i ON c.customer_id = i.customer_id
JOIN invoice_line il ON i.invoice_id = il.invoice_id
GROUP BY c.customer_id
ORDER BY tracks_purchased DESC;


-- 14. Find the average track price
SELECT AVG(unit_price) AS average_track_price
FROM invoice_line;


-- 15. Identify countries generating the highest sales
SELECT billing_country, SUM(total) AS total_sales
FROM invoice
GROUP BY billing_country
ORDER BY total_sales DESC;